// @vitest-environment jsdom
import {readFileSync} from 'node:fs';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {act,cleanup,renderHook} from '@testing-library/react';
import {useDados} from '../src/hooks/useDados';
import {parseStatus,parseTerritorio} from '../src/domain/contracts';
const ctx=vi.hoisted(()=>({load:vi.fn()}));vi.mock('../src/services/data',()=>({carregarDados:ctx.load}));
const data=()=>({status:parseStatus(JSON.parse(readFileSync('tests/fixtures/status-operacional.json','utf8'))),territorio:parseTerritorio(JSON.parse(readFileSync('public/data/territorio.json','utf8')))});
beforeEach(()=>{vi.useFakeTimers();ctx.load.mockReset();Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});});
afterEach(()=>{cleanup();vi.useRealTimers();});
it('aba aberta relê após 600s e ao retornar; limpa timer ao desmontar',async()=>{const a=data(),b=data();b.status.atualizado_em='2026-10-05T00:00:00Z';ctx.load.mockResolvedValueOnce(a).mockResolvedValue(b);const {result,unmount}=renderHook(()=>useDados());await act(async()=>{});expect(ctx.load).toHaveBeenCalledTimes(1);await act(async()=>{await vi.advanceTimersByTimeAsync(599999);});expect(ctx.load).toHaveBeenCalledTimes(1);await act(async()=>{await vi.advanceTimersByTimeAsync(1);});expect(result.current).toMatchObject({estado:'carregado',dados:b});await act(async()=>document.dispatchEvent(new Event('visibilitychange')));expect(ctx.load).toHaveBeenCalledTimes(3);unmount();await vi.advanceTimersByTimeAsync(600000);expect(ctx.load).toHaveBeenCalledTimes(3);});
it('falha de releitura preserva dados e avisa sem fabricar Normalidade',async()=>{const a=data();ctx.load.mockResolvedValueOnce(a).mockRejectedValue(Error('offline'));const {result}=renderHook(()=>useDados());await act(async()=>{});await act(async()=>{await vi.advanceTimersByTimeAsync(600000);});expect(result.current).toMatchObject({estado:'carregado',dados:a,aviso:expect.stringContaining('Última coleta disponível preservada')});});
it('snapshot mais antigo não substitui estado mais recente',async()=>{const a=data(),b=data();a.status.atualizado_em='2026-10-05T00:00:00Z';ctx.load.mockResolvedValueOnce(a).mockResolvedValue(b);const {result}=renderHook(()=>useDados());await act(async()=>{});await act(async()=>{await vi.advanceTimersByTimeAsync(600000);});expect(result.current).toMatchObject({estado:'carregado',dados:a,aviso:expect.any(String)});});
it('requisição pendente não é duplicada e primeira falha expõe indisponibilidade',async()=>{let reject!:(e:Error)=>void;ctx.load.mockImplementation(()=>new Promise((_,r)=>{reject=r;}));const {result}=renderHook(()=>useDados());await act(async()=>{await vi.advanceTimersByTimeAsync(1200000);document.dispatchEvent(new Event('visibilitychange'));});expect(ctx.load).toHaveBeenCalledTimes(1);await act(async()=>reject(Error('offline')));expect(result.current).toMatchObject({estado:'erro',mensagem:expect.stringContaining('Dados indisponíveis')});});
